# Site settings
title: Nicole Linden

name: Nicole Linden

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/nicolelinden
 - title: LinkedIn
   url: https://www.linkedin.com/in/nicole-linden

#Any buzzword skills you want to include
skills:
 - Python (Pandas, NumPy, Matplotlib, Scikit-learn, Seaborn, PyTorch)
 - Excel
 - SQL
 - Excel
 - Soccer
 

#Work experience is required
roles:
 - title: Data Analyst Intern
   start: June 2018
   end: August 2018
   employer: Carbon Health
   description: Collected, cleaned and organized complex patient data from 5 Bay Area clinics with up to 40,000 active patients. Used predictive analytics and manipulation of data in order to build a model to report the expected wait time of a patient and ultimately increase efficiency of clinics in the Bay Area. Shadowed Chief Executive Officer with opportunity to participate in key leadership meetings both internally and externally. 
 - title: Data Science Tutor
   start: 2019
   end: 2020
   employer: University of California, Berkeley Athletic Study Center
   description: Hired to tutor UC Berkeley students in Data Science coursework and helped to develop their skills in computer programming, exploratory data analysis, and introductory Statistics.
 - title: Neurology Shadow
   start: 2018
   end: 2018
   employer: Providence Saint Joseph Medical Center
   description: Shadowed a practicing neurologist at Providence Saint Joseph Medical Center. Provided opportunity to participate and assess clinical practice in both the ambulatory and hospital setting. Learned time management skills and techniques to handle high-stress situations.

#Education is required
education:
 - level: Bachelor of Arts (B.A.)
   date: 2020
   subject: Cognitive Science with a concentration in Data Science
   school: University of California, Berkeley


#This section is optional - embeds slideshows from speakerdeck


#List of interesting Github repo/projects to include - optional
github:
 - nicolelinden/nicolelinden.github.io
 


intro: |
  I have always been interested in pursuing a career in medicine but when I got to UC Berkeley, I found that I gravitated to the challenge of the more analytical classes in Computer Science and Math. So, to combine my interests, I became a Cognitive Science major taking a range of courses, from Neuroscience and Psychology to Data Science and Computational Modeling. Through my academic career and work experience as a data analyst intern, I have become inspired by data’s ability to translate an individual’s subjective thoughts into objective, quantifiable metrics. Upon graduation in May, my ideal path would combine these interests and allow me to uncover human behavior through the realm of data analytics and technological innovation. I graduated from UC Berkeley with a cumulative 3.7 GPA, developed skill in Python, and a deep understanding of math logic, translating to my ability to quickly and effectively grasp new languages and programming concepts. As Data Analyst intern at Carbon Health, I have experience organizing and cleaning data from 5 Bay Area clinics with over 40,000 active patients in order to build a model to accurately predict patient wait times given the status of the clinic. As a new grad, I am eager to enter the work world and begin my professional endeavors so that I may help integrate the fields of technology and medicine.


